version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./input:/app/input
      - ./output:/app/output
    command: chorus-detection-web
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
    restart: unless-stopped

  cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./models:/app/models
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
    command: /bin/bash
    tty: true
    stdin_open: true 